networks:
  msa_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local

services:
  mysql:
    image: bitnami/mysql:8.4
    container_name: mysql
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
    env_file: .env
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Seoul
    healthcheck:
      test: [ 'CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh' ]
      interval: 15s
      timeout: 5s
      retries: 15
    networks:
      - msa_network