@domain = http://localhost:8091
# postman
@authToken = eyJraWQiOiJiODU5NjM0Ny00ZTYyLTRjNjktYjJiMS1hNjExODE5NzNjOTkiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImF1ZCI6InlvdXR1YmUtbGVjdHVyZS1vYXV0aDIiLCJuYmYiOjE3MzEzODMwMzUsInNjb3BlIjpbIm9wZW5pZCIsInByb2ZpbGUiXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzMxMzgzMzM1LCJpYXQiOjE3MzEzODMwMzUsImp0aSI6IjFhYTBmYTMwLTZhYTktNGQ5OC04NTlmLTRlMTY1ZmE4MmRiNyJ9.sOkZrm1ZKC48BrqQ-YWhOzgu_6g7Fut5rR5CskUvsOAaiVzsJLP15UfnShz_aan6yNuIoku_spO07kyct5FDwIdWPFx0x9DPqNuem7w-RIsn272xczIUk2GtZ464dp-ubY_hZy2MYkMwmQ4DdkzeUSsZWXOHJJt_EvMY1D6OXJ_5z-4-AzOZceGZwwLNrqTvf_3opnO45_ZkcKJOYelZ-OrJ4LJvMRXh2vNqBIEgAXCOkguEVAJbhihVCdWiInN3qNOVwNCBswqdqauTQuWYHfCj-i8YtdGuGa3MK26meiyvyhov5Xmtg0xGVjZSCSDKI5JeU4_0mwBgpMVvtkHaCQ

### getAllAuthorities
GET {{domain}}/authority
Content-Type: application/json
Authorization: Bearer {{authToken}}
