@domain = http://localhost:8091
# postman
@authToken = eyJraWQiOiJiODU5NjM0Ny00ZTYyLTRjNjktYjJiMS1hNjExODE5NzNjOTkiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyOTkyIiwiYXVkIjoieW91dHViZS1sZWN0dXJlLW9hdXRoMiIsIm5iZiI6MTczMTM5MTQyNiwic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjkwMDAiLCJleHAiOjE3MzEzOTE3MjYsImlhdCI6MTczMTM5MTQyNiwianRpIjoiY2I0NTRmNTktN2FkNy00ODhlLWExYzktYTdkNGI4MmMzYjFhIn0.eXWHro1oUpy65gKQa1a5xEBREnkv6KzB13d0o5d53IuFIAxbYzZ7XvSDOr6I45WpFZKW6Q4bcXv4_hwTMEhKvozYMbm04J2cTGzwK6489pephdcYxkMFTGVuxFdFFLHJZ0Dca0VxT_cOfyWIelP1iijr1Iqi8vaR4YQ-bTsnSJi15AAs6puF5Mw-i1c42OoTMPoe5BH02eEmDIAhpIP74oRdiKpw1L5swPrmzuGLXVsycl5b0Oh031QU9QyC0j9H7rGKMVN4dpqxjt99FrVCRSbzTawQ62y-gow6p8EvDIJ0L2tZt0BpRpvF8xlB5C6QaYnvtHjkW3oacU_PN7AYEQ

### getAllRoles
GET {{domain}}/role
Content-Type: application/json
Authorization: Bearer {{authToken}}