server:
  port: 9000

spring:
  application:
    name: AuthorizationServer

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/msa_db}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:mysqluser}
    password: ${SPRING_DATASOURCE_PASSWORD:Pa55w0rd}
  sql:
    init:
      mode: always

jwt:
  encryptor:
    password: password
    salt: 626F6F746966756C

logging:
  level:
    org:
      springframework:
        security: DEBUG